item {
  name: "motor"
  id: 1
  display_name: "motor"
}

item {
  name: "car"
  id: 2
  display_name: "car"
}

item {
  name: "truck"
  id: 3
  display_name: "truck"
}

item {
  name: "bus"
  id: 4
  display_name: "bus"
}

item {
  name: "container"
  id: 5
  display_name: "container"
}

